// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0RrLZ3YXpsg_PoF90z1PqgsJ0SiBCAuo',
    appId: '1:1067332443113:web:41fc5231af36349accc978',
    messagingSenderId: '1067332443113',
    projectId: 'testing-cli-6f57b',
    authDomain: 'testing-cli-6f57b.firebaseapp.com',
    storageBucket: 'testing-cli-6f57b.appspot.com',
    measurementId: 'G-PH6VWJC4X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7VjJ6XXtXU_mHA1Oo_ZbQBv-EUHxzsRM',
    appId: '1:1067332443113:android:69ff69a7ceb25fc4ccc978',
    messagingSenderId: '1067332443113',
    projectId: 'testing-cli-6f57b',
    storageBucket: 'testing-cli-6f57b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-AQzscffvSf0PtAtj2XjhCxaiwHL3Ls',
    appId: '1:1067332443113:ios:8275a730fab698ccccc978',
    messagingSenderId: '1067332443113',
    projectId: 'testing-cli-6f57b',
    storageBucket: 'testing-cli-6f57b.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
